spring.application.name=CNCware-service-portal-backend

# PostgreSQL database
spring.datasource.url=jdbc:postgresql://localhost:5432/CNCware-service-portal
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Database initialisatie
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Security
jwt.secret=WnF1R0p1cE5yM3BMb2p4Qk1uVmpuQ0N3Z3h6VnJpVmN6bEJIM0h6Y1d6U1Z6cU5Qb2l4U2M9
jwt.expirationMinutes=30